### ISSUE TITLE
Define a Maximum Cache Size + Policies (LRU, TTL, etc)

### ISSUE THREAD

**Issue by dmoliveira** [simonster/Memoize.jl#20]
Limit the cache size.
- Add to Memoize an option for maximum cache size
- Implement `LRU`, `TTL`, among other policies.

**Comment by simonster** [comment]
Memoize.jl currently supports specifying the type of associative to use for memoization, so you can just pass in an associative that implements these caching strategies (e.g. https://github.com/JuliaLang/julia/blob/master/examples/lru.jl). To allow specifying size, it might be useful to support specifying an instance of the associative instead of the type.

**Comment by dmoliveira** [comment]
Hi @simonster. Ok, that is great :)
It was not clear that we could extend the original cache with strategies like that.
We could improve the documentation putting some nice examples.
If I have time I`ll try to do a PR for this.
I`ll close this issue now.
